#!/usr/bin/env bash

prefixes=(GITHUB ACTION)

show-vars() {
  local var

  while IFS= read -r var; do
    printf "%s: %s\n" "$var" "${!var}"
  done < <(compgen -e "$1"_)
}

for prefix in "${prefixes[@]}"; do
  show-vars "$prefix"
done
